### ISSUE TITLE
Hive 2.0

### ISSUE THREAD

**Issue by leisim** [hivedb/hive#216]
This issue is a summary of features planned for Hive 2.0

- [ ] In-memory queries
- [ ] Isolate support (VM only)
- [ ] Custom SHA-256 implementation
- [ ] `@HiveLink` annotation for 1-1 and 1-many relationships (#197)
- [ ] Auto-save option for `HiveObjecs`
- [x] `box.autoIncrement()` (#169)
- [x] `keysToDelete` parameter for `box.putAll()` to allow atomic operations
- [ ] `legacyFields` parameter for `@HiveType()` ([this comment](https://github.com/hivedb/hive/issues/180#issuecomment-575368488))
- [ ] Tests for `hive_generator`
- [ ] Tests for `hive_flutter`

Optional: 
- [ ] Automatic `TypeAdapter` registration
- [ ] Rewrite serializer (#152)
- [ ] Support for upsert (#110)
- [ ] Allow inspecting Hive with Chrome DevTools

**Comment by leisim** [comment]
Not relevant any more #246
